services:
  - type: web
    name: biskora-cookies
    env: node
    plan: starter
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
